[parity]
chain = "/etc/mintnet/mintnet.json"
base_path = "/mnt/io.parity.ethereum"

[websockets]
hosts = ["all"]
origins = ["all"]
apis = ["web3", "eth", "net", "parity", "traces", "rpc", "signer", "personal", "parity_accounts", "parity_set"]

[rpc]
cors = ["all"]
apis = ["web3", "eth", "net", "parity", "traces", "rpc", "signer", "personal", "parity_accounts", "parity_set"]
hosts = ["all"]

[footprint]
# Enables Fat DB
fat_db = "on"
# Keep all state trie data. No pruning.
pruning = "archive"
# Compute and Store tracing data. (Enables trace_* APIs).
tracing = "on"

[dapps]
disable = true

[network]
reserved_only = true
reserved_peers = "/etc/mintnet/reservedpeers.txt"